---
title: "elephants_UNUSED"
author: "Joe Gunn"
date: "2/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# UNUSED
```{r}
aem_bact_groups_rel0.1 <- aem_bact_groups[,-c(4,6,8)]
aem_firm_groups_rel0.1 <- aem_firm_groups[,-c(6,7)]
aem_proteo_groups_rel0.1 <- aem_proteo_groups[,-c(4:9,11:16,18:25)]

#PHYLUM Bacteroidetes
p_vals_bact_groups <- data.frame(numeric(length = 2))

    for (ii in 1:ncol(aem_bact_groups_rel0.1)) {
  
      col = aem_bact_groups_rel0.1[,ii] #this tells the for loop that it should iterate through columns in the data set
      lm_temp <- lm(col ~ Group, data = aem_bact_groups_rel0.1) #tells the for loop to run linear model  for each column specified above
      fstat <- summary(lm_temp)$fstatistic #extracts f statistics
      p_value <- pf(fstat[1], fstat[2], fstat[3], lower.tail = F)
      p_vals_bact_groups[ii,] <- p_value
    }
```

#Make Box Plots for ALL ORDERS
```{r}
#Log-transform y axis so that all values will show up
groups_bacteroidetes_order_abun <- read_excel("groups_bacteroidetes_order_abun.xlsx")
groups_bacteroidetes_order_abun <- groups_bacteroidetes_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))

groups_firmicutes_order_abun <- read_excel("groups_firmicutes_order_abun.xlsx")
groups_firmicutes_order_abun <- groups_firmicutes_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))

groups_proteobacteria_order_abun <- read_excel("groups_proteobacteria_order_abun.xlsx")
groups_proteobacteria_order_abun  <- groups_proteobacteria_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))


#PHYLUM Bacterioidetes
bact_group_plots <- ggplot(groups_bacteroidetes_order_abun, aes(x = order, y = sqrt_abundance, fill = group)) + 
  geom_boxplot(outlier.shape = NA, show.legend = T, alpha = 0.8) + 
  geom_point(position = position_dodge(width = 0.75), show.legend = F) +
  theme_set(theme_cowplot(12)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Orders by Elephant Group", fill = "Elephant Group") + 
  scale_fill_manual(values = c("green", "purple", "red", "goldenrod")) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.title.y = element_blank()) + 
  theme(legend.position = c(0.65,0.7)) + 
  theme(axis.text.x = element_text(face = "italic"))  


#PHYLUM Firmicutes
firm_group_plots <- ggplot(groups_firmicutes_order_abun, aes(x = order, y = sqrt_abundance, fill = group)) + 
  geom_boxplot(outlier.shape = NA, show.legend = F, alpha = 0.8) + 
  geom_point(position = position_dodge(width = 0.75), show.legend = F) +
  theme_set(theme_cowplot(12)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_fill_manual(values = c("green", "purple", "red", "goldenrod")) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.title.y = element_blank()) + 
  theme(axis.text.x = element_text(face = "italic"))

#PHYLUM Proteobacteria
proteo_group_plots <- ggplot(groups_proteobacteria_order_abun, aes(x = order, y = sqrt_abundance, fill = group)) + 
  geom_boxplot(outlier.shape = NA, show.legend = F, alpha = 0.8) + 
  geom_point(position = position_dodge(width = 0.75), show.legend = F) +
  theme_set(theme_cowplot(12)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_fill_manual(values = c("green", "purple", "red", "goldenrod")) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.title.y = element_blank()) + 
  theme(axis.text.x = element_text(face = "italic"))

jpeg("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/NEW_STATS/AEMB_FINAL_STATS/African_Elephant_Microbiome/phylum_group_plots.jpeg", width=2000, height=3000, units='px', res=250) 

plot_grid(bact_group_plots, firm_group_plots, proteo_group_plots, nrow = 3, labels = c("A", "B", "C"))

dev.off()


#For combining figures

phy_group_plot <- plot_grid(bact_group_plots, firm_group_plots, proteo_group_plots, nrow = 3, labels = c("D", "E", "F"))


##WE did not look for genera within Saprospirales, because it is in such low abundance (only found in n = 8 samples)



###COMBINE PHYLUM PLOTS

pdf("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/NEW_STATS/AEMB_FINAL_STATS/African_Elephant_Microbiome/phy_combined_plots.pdf", width=15, height=20) 

plot_grid(phy_species_plot, phy_group_plot, ncol = 2)

dev.off()
```

#Make Box Plots for ALL ORDERS
```{r}
#Log-transform y axis so that all values will show up

#PHYLUM Bacteroidetes
species_bacteroidetes_order_abun <- read_excel("species_bacteroidetes_order_abun.xlsx")
species_bacteroidetes_order_abun <- species_bacteroidetes_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))

#PHYLUM Firmicutes
species_firmicutes_order_abun <- read_excel("species_firmicutes_order_abun.xlsx")
species_firmicutes_order_abun <- species_firmicutes_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))

#PHYLUM Proteobacteria
species_proteobacteria_order_abun <- read_excel("species_proteobacteria_order_abun.xlsx")
species_proteobacteria_order_abun <- species_proteobacteria_order_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))
 
#Make box-plots of Orders for African Elephant Species

#Bacteroidetes
species_bacteroidetes_box_plots <- ggplot(species_bacteroidetes_order_abun, aes(x = order, y = sqrt_abundance, fill = species)) + 
  geom_boxplot(show.legend = T, outlier.shape = NA, alpha = 0.8) + 
  geom_point(aes(color = sex), position = position_dodge(width = 0.8), show.legend = F) +
  theme_set(theme_cowplot(12)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(fill = "Elephant Sex", title = "Orders by Elephant Species", y = "Bacteroidetes Abundance") + 
  scale_color_manual(values = c("black", "black")) +
  scale_fill_manual(values = c("red", "blue")) + 
  theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.65,0.7)) + 
  theme(legend.text = element_text(face = "italic")) + 
  theme(axis.text.x = element_text(face = "italic")) 

#Firmicutes
species_firmicutes_box_plots <- ggplot(species_firmicutes_order_abun, aes(x = order, y = sqrt_abundance, fill = species)) + 
  geom_boxplot(show.legend = F, outlier.shape = NA, alpha = 0.8) + 
  geom_point(aes(color = species), position = position_dodge(width = 0.8)) +
  theme_set(theme_cowplot(12)) + 
  scale_color_manual(values = c("black", "black")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(y = "Firmicutes Abundance") + 
  scale_fill_manual(values = c("red", "blue")) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.text.x = element_text(face = "italic"))


#Proteobacteria
species_proteobacteria_box_plots <- ggplot(species_proteobacteria_order_abun, aes(x = order, y = sqrt_abundance, fill = Species)) + 
  geom_boxplot(show.legend = F, outlier.shape = NA, alpha = 0.8) + 
  geom_point(aes(color = Species), position = position_dodge(width = 0.8)) +
  theme_set(theme_cowplot(12)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(y = "Proteobacteria Abundance") +
  scale_color_manual(values = c("black", "black")) +
  scale_fill_manual(values = c("red", "blue")) + 
  theme(axis.title.x = element_blank()) + 
  theme(axis.text.x = element_text(face = "italic"))
  

jpeg("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/NEW_STATS/AEMB_FINAL_STATS/African_Elephant_Microbiome/phylum_species_plots_withPOINTS.jpeg", width=2000, height=3000, units='px', res=250) 

plot_grid(species_bacteroidetes_box_plots, species_firmicutes_box_plots, species_proteobacteria_box_plots, nrow = 3, labels = c("A", "B", "C"))

dev.off()


#For combining figures
phy_species_plot <- plot_grid(species_bacteroidetes_box_plots, species_firmicutes_box_plots, species_proteobacteria_box_plots, nrow = 3, labels = c("A", "B", "C"))
```

# Make box plots for ALL GENERA
```{r}
#square root transform the y-axis
species_bacillales_genera_abun <- read_excel("../excel_data/abundance/species_bacillales_genera_abun.xlsx")
species_bacillales_genera_abun <- species_bacillales_genera_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))

species_lactobacillales_genera_abun <- read_excel("../excel_data/abundance/species_lactobacillales_genera_abun.xlsx")
species_lactobacillales_genera_abun <- species_lactobacillales_genera_abun %>% mutate(log_abundance = log10(abundance), sqrt_abundance = sqrt(abundance))



#Plots of genera within Firmicutes Orders by African Elephant Species
bacillales_plot <- ggplot(species_bacillales_genera_abun, aes(x = order, y = sqrt_abundance, fill = species)) + 
  geom_boxplot(outlier.shape = NA, show.legend = T) + 
  theme_set(theme_cowplot(12)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Genera of Order Bacillales", fill = "Elephant Species", x = "Genus", y = "Mean Abundance") + 
  scale_fill_manual(values = c("red", "blue")) + 
  theme(legend.text = element_text(face = "italic")) + 
  theme(axis.text.x = element_text(face = "italic")) + 
  theme(legend.position = c(0.05, 0.7))

lacto_plot <- ggplot(species_lactobacillales_genera_abun, aes(x = order, y = sqrt_abundance, fill = species)) + 
  geom_boxplot(outlier.shape = NA, show.legend = F) + 
    theme_set(theme_cowplot(12)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    labs(title = "Genera of Order Lactobacillales", x = "Genus", y = "Mean Abundance") +
    scale_fill_manual(values = c("red", "blue")) + 
    theme(axis.text.x = element_text(face = "italic"))


pdf("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/Attempt_2/firmicutes_genera_byspecies.pdf", width=10, height=12) 

plot_grid(bacillales_plot, lacto_plot, nrow = 2, labels = c("A", "B"))

dev.off()
```

```{r}
#Include Sex in Habitat and Diet Alpha diversity graphs, becasue sex is significant in some of the variables. This will be a supplementary figure.

#Make the Figures

alpha_diet_sex <- ggplot(shan_div_diet, aes(x = Raider, y = shannon, color = Sex)) + geom_boxplot(outlier.shape = NA) + labs(x = "Diet", y = "Shannon Diversity") + scale_color_manual(values = c("magenta", "mediumseagreen"))

alpha_habitat_sex <- ggplot(shan_div_diet, aes(x = Habitat, y = shannon, color = Sex)) + geom_boxplot(outlier.shape = NA) + labs(x = "Habitat", y = "Shannon Diversity") + scale_color_manual(values = c("magenta", "mediumseagreen"))

#Print the Figures

jpeg("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/NEW_STATS/AEMB_FINAL_STATS/African_Elephant_Microbiome/alpha_by_sex.jpeg", width=3700, height=3700, units='px', res=500) 

plot_grid(alpha_diet_sex, alpha_habitat_sex, nrow = 2, labels = c("A", "B"))

dev.off()
```

# Graph NMDS for Species, Diet, and Habitat

```{r}
##################################################################

centroids_all_species <- aggregate(cbind(NMDS1, NMDS2) ~ Species, merge_all, mean)
gg_all_species <- merge(merge_all, aggregate(cbind(mean.x = NMDS1, mean.y = NMDS2) ~ Species, merge_all, mean), by = "Species")

centroids_all_diet <- aggregate(cbind(NMDS1, NMDS2) ~ Raider, merge_all, mean)
gg_all_diet <- merge(merge_all, aggregate(cbind(mean.x = NMDS1, mean.y = NMDS2) ~ Raider, merge_all, mean), by = "Raider")

centroids_all_hab <- aggregate(cbind(NMDS1, NMDS2) ~ Habitat, merge_all, mean)
gg_all_hab <- merge(merge_all, aggregate(cbind(mean.x = NMDS1, mean.y = NMDS2) ~ Habitat, merge_all, mean), by = "Habitat")



levels(merge_all$Species) <- c("L. africana", "L. cyclotis")
levels(merge_all$Raider) <- c("Non-Crop-Raider", "Crop-Raider")

all_perm_species <- ggplot(gg_all_species, aes(NMDS1, NMDS2, color = Species)) + 
  geom_point(size = 2) + 
  geom_point(aes(x = mean.x, y = mean.y), size = 2) + 
  geom_segment(aes(x = mean.x, y = mean.y, xend = NMDS1, yend = NMDS2)) + 
  theme_set(theme_cowplot(12)) + 
  scale_color_manual(values = c("red2", "blue2")) + 
  labs(color = "Elephant Species", x = "NMDS 1", y = "NMDS 2", title = "Beta Diversity: Full Model") + 
  theme(axis.title.x = element_blank()) + 
  theme(legend.text = element_text(face = "italic")) +
  theme(legend.position=c(0.59,0.15)) + 
  theme(plot.title = element_text(size = 20, hjust = 0.5, face = "bold"))

all_perm_diet <- ggplot(gg_all_diet, aes(NMDS1, NMDS2, color = Raider)) + 
  geom_point(size=2) +
  geom_point(aes(x = mean.x, y = mean.y), size = 2) + 
  geom_segment(aes(x = mean.x, y = mean.y, xend = NMDS1, yend = NMDS2)) + 
  theme_set(theme_cowplot(12)) + 
  scale_color_manual(values = c("midnightblue", "deeppink1")) + 
  labs(color = "Elephant Diet", x = "NMDS 1", y = "NMDS 2") + 
  theme(axis.title.x = element_blank()) + 
  theme(legend.position=c(0.59,0.15))

all_perm_habitat <- ggplot(gg_all_hab, aes(NMDS1, NMDS2, color = Habitat)) + 
  geom_point(size = 2) + 
  geom_point(aes(x = mean.x, y = mean.y), size = 2) + 
  geom_segment(aes(x = mean.x, y = mean.y, xend = NMDS1, yend = NMDS2)) + 
  theme_set(theme_cowplot(12)) + 
  scale_color_manual(values = c("forestgreen", "coral2")) + 
  labs(color = "Elephant Habitat", x = "NMDS 1", y = "NMDS 2") + 
  theme(legend.position=c(0.59,0.15))


pdf("/Users/joegunn/Desktop/Grad_School_Stuff/Projects/Elephant_Microbiome/Attempt_2/beta_diversity_forALL.pdf", width=7, height=13) 

plot_grid(all_perm_species, all_perm_diet, all_perm_habitat, nrow = 3, labels = c("A", "B", "C"))

dev.off()

beta_all_plot <- plot_grid(all_perm_species, all_perm_diet, all_perm_habitat, nrow = 3, labels = c("A", "B", "C"))

```